### ISSUE TITLE
 从亚洲起飞的航班位于美洲时显示的坐标位置可以更改

### ISSUE THREAD

**Issue by rickliu2000** [sparrowhe/oscar-map-v2#4]
问题如图 QAQ
这时候飞机坐标可以改在东边美洲的位置，这样航路显示会更漂亮
![image](https://user-images.githubusercontent.com/13375457/164911888-dcc6385e-8d33-4383-b960-4be9416bd8a9.png)
![image](https://user-images.githubusercontent.com/13375457/164911994-b71088b4-c353-4941-96b6-ce27b61467ce.png)

**Comment by sparrowhe** [comment]
这是web墨卡托投影的问题，暂不考虑调整
